name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.5'
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - 'pypy-3.6'
        - 'pypy-3.7'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pycron --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 pycron --count --exit-zero --max-complexity=20 --max-line-length=120 --statistics
    - name: Test with Pytest
      run: |
        pytest -sv --flake8 --cov-report term-missing --junit-xml=nosetests-ut.xml --cov=. --cov-branch --cov-report=xml:coverage-ut.xml tests/
    # - name: Coveralls
    #   uses: AndreMiras/coveralls-python-action@develop
    #   with:
    #     parallel: true
    #     flag-name: run-${{ matrix.test_number }}

  # finish:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Coveralls Finished
  #     uses: AndreMiras/coveralls-python-action@develop
  #     with:
  #       parallel-finished: true
